version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: security-postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: security-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
