spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_alerts
    username: postgres
    password: postgres
    
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

security:
  jwt:
    secret: ${JWT_SECRET:changeme}
    expiration: 3600


